---
title: "Yuqi_trivial"
author: "Yuqi Miao ym2771"
date: "4/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data = readxl::read_xlsx("Proj 4 data.xlsx") %>% 
  janitor::clean_names()
```

## Baseline heatmap

```{r, include = F}
symmat_heatmap = function(mat, name, size){
  dat = as_tibble(mat) %>%
    mutate(rows = colnames(mat))
  dat_melt = as_tibble(melt(dat)) %>%
    mutate(rows = factor(rows))
  g = ggplot(data=dat_melt,
             aes(x = variable, y = rows, fill = value)) +
    geom_tile() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = size),
          axis.text.y = element_text(angle = 45, hjust = 1, size = size))+
    xlim(levels(dat_melt$rows))+
    ggtitle(name) + scale_fill_gradient2(low="blue",mid = "white", high="red")
  g
}
```

This heatmap aims to see the correlation/covariance between individuals in the same school at baseline to get a initial understanding of the intra-cluster correlaiton
```{r}
data_cov = data %>% 
  pivot_wider(names_from = time,
              values_from = sfd,
              id_cols = c(id, school),
              names_prefix = "time") %>% 
  filter(!is.na(time1) & !is.na(time2) & !is.na(time3)) %>% 
  # remove all subjects with NAs
  arrange(school)

sfd = t(data_cov[,3:5])
colnames(sfd) = data_cov$id

g_cov = symmat_heatmap(cov(sfd), 
               name = "Covariance of sfd aligned by school",
               size = 5)

g_cor = symmat_heatmap(cor(sfd), 
               name = "Correlation of sfd aligned by school",
               size = 5)
```

* Not very informative

# GLMM fitting


$$
\begin{aligned}
\log\frac{\pi_{ijk}}{1-\pi_{ijk}}&=\beta_0\\
&+\beta_1t_{ijk}\\
&+\beta_2I(\text{trt}=1)_i\\\
&+\gamma_{0j}\\
&+\epsilon_{ijk}
\end{aligned}
$$



Model 1 continuous t, 
Model 2 discrete t

```{r}
# random intercept model
data_fit = data %>% 
  mutate(time_categ = factor(time, levels = 1:3,
                             labels = c("base","6m", "12m")))
fit1 <- glmer(cbind(sfd, 14-sfd)~ group*time +(1|school) +(1|id), 
                  family = 'binomial', data = data_fit)
summary(fit1) 

fit2 <- glmer(cbind(sfd, 14-sfd)~ group*time_categ + (1|school) +(1|id), 
                  family = 'binomial', data = data_fit)
summary(fit2) 
```


```{r}
fit3 <- glmer(sfd ~ school + group*time +(1|id),  # not converge +(1|school)
                  family = 'poisson', data = data_fit)
summary(fit3) 

fit4 <- glmer(sfd ~ school + group*time_categ +(1|id), # not converge +(1|school)
                  family = 'poisson',data = data_fit)
summary(fit4) 
```

